### ISSUE TITLE
External db client cert and key environment variables?

### ISSUE THREAD

**Issue by kirkre** [bitnami/bitnami-docker-drupal-nginx#10]
I want to set this to use an existing postgresql db. The environment variables listed under 'use an existing db' look appropriate, but there are no environment variables listed for the client certificate and client key, which our db requires. What environment variables can I use for this? Also what environment variable to set ssl yes for the db? The mysql client environment variables include the following for certs:

MYSQL_CLIENT_ENABLE_SSL
MYSQL_CLIENT_SSL_CA_FILE
MYSQL_CLIENT_SSL_CERT_FILE
MYSQL_CLIENT_SSL_KEY_FILE

But except for DRUPAL_DATABASE_TLS_CA_FILE I do not see these options listed for an external db.

Thanks!

**Comment by javsalgar** [comment]
Hi,

Let me see if I understand this. So, the issue would be that you would need a certificate for authenticating with the database instead of a username and a password, is that correct? 

From what I see in our code

```
  'pdo' => array (
    PDO::MYSQL_ATTR_SSL_CA => '${DRUPAL_DATABASE_TLS_CA_FILE}',
    PDO::MYSQL_ATTR_SSL_VERIFY_SERVER_CERT => 0
  )
```

We would need to add these two probably

```
MYSQL_ATTR_SSL_CERT
MYSQL_ATTR_SSL_KEY
```

I will open a task for investigating this. I cannot guarantee an ETA as it is not a critical feature, but I will update this ticket as soon as we have more news. Thank you for reporting.

**Comment by kirkre** [comment]
Hi javsalgar. The postgres db requires the certificates and key in addition to a username and password. I take it more than just the environment variable needs to be added to the code to make this work? The environment variables also need to link to the proper drupal settings? Thanks.

**Comment by javsalgar** [comment]
Hi,

If you want to try, then you should go to the line in libdrupal.sh that shows this

```
  'pdo' => array (
    PDO::MYSQL_ATTR_SSL_CA => '${DRUPAL_DATABASE_TLS_CA_FILE}',
    PDO::MYSQL_ATTR_SSL_VERIFY_SERVER_CERT => 0
  )
```

And change it to

```
  'pdo' => array (
    PDO::MYSQL_ATTR_SSL_CA => '${DRUPAL_DATABASE_TLS_CA_FILE}',
    PDO::MYSQL_ATTR_SSL_VERIFY_SERVER_CERT => 0,
    PDO:: MYSQL_ATTR_SSL_KEY => '${DRUPAL_DATABASE_TLS_KEY_FILE}',
    PDO:: MYSQL_ATTR_SSL_CERT =>  '${DRUPAL_DATABASE_TLS_CERT_FILE}'
  )
```

We would need to add these two variables, DRUPAL_DATABASE_TLS_KEY_FILE and DRUPAL_DATABASE_TLS_CERT_FILE

**Comment by kirkre** [comment]
Thanks javsalgar this does help. My only question now is whether these options that are seemingly made for mysql will work for postgres. I'm now using my own code to install drupal with a modified fork of bitnami-docker-nginx, but I'm back to the same issue of accessing the postgres db with ssl and cert.

One thing I am wondering about bitnami-docker-drupal-nginx, how is it intended that users modify the drupal site installation with  additional modules for instance. Is this intended for the most basic Drupal sites only without any options like that? I'm using composer and drush to script drupal site installation, but if you have a better plan in mind for customized sites I would love to find out what that plan is, which so far I don't see described in the docs.

Thanks,

Kirk

**Comment by javsalgar** [comment]
Hi,

In order to add customizations, you could use the init scripts feature. https://github.com/bitnami/bitnami-docker-drupal-nginx/blob/master/9/debian-10/rootfs/post-init.sh

If you mount scripts `/docker-entrypoint-init.d`, they will be executed on the first boot. Would that work for your case?

**Comment by carrodher** [comment]
Hi, unfortunately, the task is still on our backlog and there are no plans to work on it in the short/middle term.

In the same way, please, [note the Bitnami team is not actively working on new features/improvements nor providing support through GitHub Issues for this project](https://github.com/bitnami/bitnami-docker-drupal-nginx#community-supported-solution) since this asset was marked as a “Community supported solution”.

At this point, the best option to fix any issue or add a new feature is to contribute create a PR; the Bitnami team will be happy to review it and provide feedback.
