### ISSUE TITLE
PHP 7.4

### ISSUE THREAD

**Issue by mralexho** [bitnami/bitnami-docker-drupal-nginx#9]
Hello, 

Just out of curiosity why do you run on PHP 7.3 vs 7.4?

My team is deciding on whether to rebuild the image or leave as-is. We're not using additional features from 7.4 like typed properties and arrow functions but know there's a slight performance improvement.

Thanks!

**Comment by carrodher** [comment]
Hi, no strong reason behind that decision, we are using the recommended versions by the upstream developers, see https://www.drupal.org/docs/system-requirements/php-requirements#php_required. In this case there are several recommended versions for both Drupal 8.X and 9.X.
When the first version of a new Drupal major branch appears probably the default PHP version was 7.3, since it is working fine and there are no users asking for PHP 7.4 with a strong reason we didn't modify that. If there is any reason or use case you want to cover I can create an internal task to investigate that replacement

**Comment by mralexho** [comment]
@carrodher thanks for the quick response! We don't have a strong reason to modify but thanks for explaining.
